name: Build ArdentLinux Container

on:
  workflow_call:
    inputs:
       export_path:
           required: true
           type: string
           description: 'Cache Export PATH'
       stack_image:
           required: true
           type: string
           description: 'Image name'

  workflow_dispatch:

env:
  DOCKER_CACHE_PATH: ${{ inputs.export_pathe }}

jobs:
  build_container:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Cache Arena
          uses: actions/cache@v3
          id: cache-area
          with:
            path: ${{ inputs.export_path }}
            key: ${{ inputs.stack_image }}

        - name: Building Container...
          run: |
            docker build -t atolycs/ardentlinux:build \
                  -f ./.github/workflows/container/Dockerfile \
                  ./.github/workflows/container

        - name: Cache Container
          if: steps.cache-area.outputs.cache-hit != 'true'
          run: |
            docker save atolycs/ardentlinux:build -o ${DOCKER_CACHE_PATH}

