on:
   workflow_dispatch:

jobs:
    building_container:
       name: Build ArchLinux Container
       runs-on: ubuntu-22.04
       steps:
          - name: Checkout Dockerfile
            uses: actions/checkout@v3

          - name: Build Container
            run: |
                docker build -t atolycs/build-env:latest -f ./.github/workflows/container/Dockerfile ./.github/workflows/container/
