on:
   workflow_dispatch:
   issues:
        types: [opened, reopened]

jobs:
    building_container:
       name: Build ArchLinux Container
       steps:
          - name: Checkout Dockerfile
            uses: actions/checkout@v3

    build_length:
       name: Get Request Build List
       runs-on: ubuntu-22.04
       outputs:
           values: ${{ steps.issue_build_request.outputs.build_list }}
       steps: 
            - name: Checkout
              uses: actions/checkout@v3
            - name: Get Issue Comment
              id: issue_build_request
              env:
                NUMBER: ${{ github.event.issue.number }}
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                _BUILD_LIST=$(gh issue view ${NUMBER} | grep "Build Request:" \
                     | sed -e "s/Build Request: //g" \
                           -e "s/ //g" \
                           -e "s/^/\[\"/g" \
                           -e "s/$/\"\]/g" 
                           -e "s/,/\",\"/g")
                echo "build_list=$_BUILD_LIST" >> $GITHUB_OUTPUT

            - name: Check Build Output
              env:
                BUILD_LIST: ${{ steps.issue_build_request.outputs.build_list }}
              run: |
                echo $BUILD_LIST
    execute:
       name: Build
       needs: [build_length, building_container]
       runs-on: ubuntu-22.04
       strategy:
           matrix:
              build_packs: ${{fromJSON(needs.build_length.outputs.values)}}
       steps:
          - name: Test with ${{ matrix.build_packs }}
            env:
              BUILD_NAME: ${{ matrix.build_packs }}
            run: |
              echo "Running: ${BUILD_NAME}"
              

