on:
   workflow_dispatch:
   issues:
        types: [opened, reopened]

jobs:
    building_container:
       name: Build Container
       uses: ./.github/workflows/build-package.yml

    build_length:
       name: Get Request Build List
       runs-on: ubuntu-22.04
       outputs:
           values: ${{ steps.issue_build_request.outputs.build_list }}
       steps: 
            - name: Checkout
              uses: actions/checkout@v3
            - name: Get Issue Comment
              id: issue_build_request
              env:
                ISSUE_NUMBER: ${{ github.event.issue.number }}
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                _BUILD_LIST=$(gh issue view ${ISSUE_NUMBER} | grep "Build Request:" \
                                 | sed -e "s/Build Request: //g" \
                                       -e "s/^/\[\"/g" \
                                       -e "s/\,/\"\,\"/g" \
                                       -e "s/.$/\"\]/g" \
                                       -e "s/ //g")
                echo "LIST: ${_BUILD_LIST}"
                echo "build_list=$_BUILD_LIST" >> $GITHUB_OUTPUT

            - name: Check Build Output
              env:
                BUILD_LIST: ${{ steps.issue_build_request.outputs.values }}
              run: |
                echo $BUILD_LIST
    execute:
       name: Build
       needs: [build_length, building_container]
       runs-on: ubuntu-22.04
       strategy:
           matrix:
              build_packs: ${{fromJSON(needs.build_length.outputs.values)}}
       steps:
          - name: Cache Restore
            uses: actions/cache@v3
            with:
              path: archstack-image
              keys: dockerstack-archstack-image

          - name: Test with ${{ matrix.build_packs }}
            env:
              BUILD_NAME: ${{ matrix.build_packs }}
            run: |
              #              echo "Running: ${BUILD_NAME}"
              docker run -t --rm atolycs/ardentlinux:build
              

