on:
   workflow_dispatch:
   issues:
      - [opened]

jobs:
    gen_token:
       runs-on: ubuntu-22.04
       outputs:
          output1: ${{ steps.gend_token.outputs.test }}
       steps: 
            - name: Checkout
              uses: actions/checkout@v3
            - name: Get Issue Comment
              env:
                NUMBER: ${{ github.event.issue.number }}
              run: |
                gh issue view ${NUMBER}

              

