on:
   workflow_dispatch:

jobs:
    gen_token:
       runs-on: ubuntu-22.04
       outputs:
          output1: ${{ steps.gend_token.outputs.test }}
       steps: 
            - name: Generate One Time Token
              id: generate_token
              uses: tibdex/github-app-token@v1
              with:
                app_id: ${{ secrets.APP_ID }}
                private_key: ${{ secrets.PRIVATE_KEY }}
            - name: Use token
              id: gend_token
              env:
                TOKEN: ${{ steps.generate_token.outputs.token }}
              run: |
                echo "Masked Token: ${TOKEN}"
                echo "::set-output name=test::${TOKEN}"
    create_issue:
         runs-on: ubuntu-22.04
         needs: gen_token
         steps:
             - name: Create Issue on bot
               env:
                 GH_TOKEN: ${{ needs.gen_token.outputs.output1 }}
               run: |
                 gh issue create \
                     --title "This is Test Bot" \
                     --body "Welcome to Github Apps"

