on:
   workflow_dispatch:

jobs:
    gen_token:
       runs-on: ubuntu-22.04
       outputs:
          output1: ${{ steps.gend_token.outputs.test }}
       steps: 
            - name: Checkout
              uses: actions/checkout@v3

            - name: Generate One Time Token
              id: generate_token
              uses: tibdex/github-app-token@v1
              with:
                app_id: ${{ secrets.APP_ID }}
                private_key: ${{ secrets.PRIVATE_KEY }}
            - name: Use token
              id: gend_token
              env:
                TOKEN: ${{ steps.generate_token.outputs.token }}
              run: |
                echo "Masked Token: ${TOKEN}"
                echo "::set-output name=test::${TOKEN}"
            - name: Create Issue on bot
              env:
                GH_TOKEN: ${{ steps.generate_token.outputs.token }}
              run: |
                echo "Check to [here](https\://github.com/atolycs/ardent-repo.git) and Run\`sudo pacman -Sy\`<br>If No problem then add Label\`lgtm\`" | gh issue create \
                   --title "[$(date +%Y%m%d-%H%m%S)] ArdentLinux Builded." \
                   --body-file - 
#                 gh issue create \
#                     --title "This is Test Bot" \
#                     --body "Welcome to Github Apps"
               
#    create_issue:
#         runs-on: ubuntu-22.04
#         needs: gen_token
#         steps:
#             - name: Create Issue on bot
#               env:
#                 GH_TOKEN: ${{ needs.gen_token.outputs.output1 }}
#               run: |
#                 echo ${GH_TOKEN}
#                 gh issue create \
#                     --title "This is Test Bot" \
#                     --body "Welcome to Github Apps"

