on:
   workflow_dispatch:

jobs:
    runs-on: ubuntu-22.04
    generate_token:
        steps: 
            - name: Generate One Time Token
              id: generate_token
              uses: tibdex/github-app-token@v1
              with:
                app_id: ${{ secrets.APP_ID }}
                private_key: ${{ secrets.PRIVATE_KEY }}
            - name: Use token
              env:
                TOKEN: ${{ steps.generate_token.outputs.token }}
              run: |
                echo "Masked Token: ${TOKEN}"
    
